### ISSUE TITLE
Status icon doesn't show on Ubuntu 16.04

### ISSUE THREAD

**Issue by tilusnet** [eliostvs/tomate-statusicon-plugin#2]
I can't make this appear.
Any hint appreciated, happy to investigate.

**Comment by eliostvs** [comment]
Are you using Unity? This plugin uses Gtk.StatusIcon widget that seems not work with Unity. I recommend that you use my [other plugin](https://github.com/eliostvs/tomate-indicator-plugin) if you are using Unity.

**Comment by tilusnet** [comment]
I am using Unity.
It's a shame the status icon doesn't work; I tried the icon indicator, unfortunately it's barely visible.
Thanks anyway!

**Comment by eliostvs** [comment]
The status icon plugin is basically the same thing but uses other type of widget. Another option is the [launcher plugin](tomate-launcher-plugin) that uses the dock icon.

**Comment by eliostvs** [comment]
I'm closing this issue, if you still need help let me know.
